### ISSUE TITLE
License

### ISSUE THREAD

**Issue by laurensvalk** [turmary/am18x-lib#2]
What is the license of this library?

It would be cool to use for Lego Mindstorms EV3, to make a bare metal firmware that boots instantly, instead of taking a long time to boot an entire Linux distro.

I was able to build a UART echo example using this repository, but I wasn't sure if I should proceed without knowing the open source status. Thanks!

**Comment by turmary** [comment]
hi laurensvalk,
  I added a MIT license for this project, you can use it for whatever if you want.

**Comment by laurensvalk** [comment]
Very cool, thank you!

Last week I put together a bare arm port for Pybricks for EV3 (AM1808) at https://github.com/pybricks/pybricks-micropython/pull/241. This does not include any hardware support yet. Let's see if we can use `am18x-lib` for that :)

What kind of devices with AM18X did you use?

**Comment by turmary** [comment]
I use the board from TI -- AM1808-EVM. 
For a short description, please see:
https://www.digikey.com/en/htmldatasheets/production/710550/0/0/1/am1808-evm-qsg

Most am18x-lib examples only run in the small In-Chip SRAM with size 128KB.
I doubt Pybricks is too big to fit into the SRAM, maybe you need to solve the DDR settings first of all.

**Comment by laurensvalk** [comment]
Thanks for the hint! That's currently a little bit outside my expertise, but either way your `am18x-lib` seems like a good resource for inspiration :slightly_smiling_face:

Combined with the following two resources, everything exists for the EV3 (with AM1808), but it will be a bit of a puzzle to untangle it from either this EV3RT RTOS variant or the ev3dev Linux-based variant:
- [ev3dev](https://www.ev3dev.org/docs/kernel-hackers-notebook/ev3dev-linux-kernel/): Well documented resources for EV3 on debian Linux.
- [EV3RT](https://github.com/pybricks/ev3rt-lib): RTOS (not Linux). Closer to the metal, but drivers mixed in with RTOS.

The goal is to extract the relevant parts from these resources to write basic EV3 hardware drivers for Pybricks. Potentially using your `am18x-lib` as a clean, minimalist starting point.

So it will be more like a "microcontroller" approach. Specifically, the goal would be to eventually end up with non-blocking (e.g. interrupt or dma based) implementations for functions like:

```c
void pbdrv_uart_set_baud_rate(pbdrv_uart_dev_t *uart, uint32_t baud);
pbio_error_t pbdrv_uart_read_begin(pbdrv_uart_dev_t *uart, uint8_t *msg, uint8_t length, uint32_t timeout);
pbio_error_t pbdrv_uart_read_end(pbdrv_uart_dev_t *uart);
```

And similar for PWM, I2C, and so on.

All the higher level code can be shared with the other LEGO hubs, which is largely already done.
